export const MOVE_BOOK = "MOVE_BOOK";
export const SEARCH_FOR_BOOK = "SEARCH_FOR_BOOK";
export const FETCH_BOOKS_FAILED = "FETCH_BOOKS_FAILED";

export const SET_BOOKS = "SET_BOOKS";
export const REMOVE_BOOK = "REMOVE_BOOK";
export const RESET_SEARCH_BOOKS = "RESET_SEARCH_BOOKS";
